name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - opencv
  - tensorflow
  - pip
  - pip:
      - streamlit
      - streamlit-webrtc
      - opencv-python
      - mediapipe
      - numpy
      # - tensorflow
      - pandas
      - matplotlib
      - mediapipe
      - gdown
      - streamlit-component-lib
    
