name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - tensorflow
  - opencv
  - gdown
  - pip  # Enables pip for packages unavailable through Conda
  - pip:
      - streamlit
      - streamlit-webrtc
      - opencv-python
      - mediapipe

    
