name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - tensorflow
  - opencv
  - numpy
  - pandas
  - matplotlib
  - pip
  - pip:
      - streamlit
      - streamlit-webrtc
      - mediapipe
      - gdown
      - streamlit-component-lib
