name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - tensorflow  # Install TensorFlow via conda
  - pip:
      - streamlit
      - streamlit-webrtc
      - mediapipe
      - numpy
      - pandas
      - matplotlib
      - gdown
      - streamlit-component-lib
      - opencv-python
