name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - streamlit
      - streamlit-webrtc
      - opencv-python
      - mediapipe
      - numpy
      - tensorflow
      - pandas
      - matplotlib
      - mediapipe
      - gdown
    
    
    
